
# This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

# It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.

# You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where not to step.

# Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.

# Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical series of motions (your puzzle input) for the head, you can determine how the tail will move.

# Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):

# ....
# .TH.
# ....

# ....
# .H..
# ..T.
# ....

# ...
# .H. (H covers T)
# ...
# If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:

# .....    .....    .....
# .TH.. -> .T.H. -> ..TH.
# .....    .....    .....

# ...    ...    ...
# .T.    .T.    ...
# .H. -> ... -> .T.
# ...    .H.    .H.
# ...    ...    ...
# Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:

# .....    .....    .....
# .....    ..H..    ..H..
# ..H.. -> ..... -> ..T..
# .T...    .T...    .....
# .....    .....    .....

# .....    .....    .....
# .....    .....    .....
# ..H.. -> ...H. -> ..TH.
# .T...    .T...    .....
# .....    .....    .....
# You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.

# For example:

# R 4
# U 4
# L 3
# D 1
# R 4
# D 1
# L 5
# R 2
# This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):

# == Initial State ==

# ......
# ......
# ......
# ......
# H.....  (H covers T, s)

# == R 4 ==

# ......
# ......
# ......
# ......
# TH....  (T covers s)

# ......
# ......
# ......
# ......
# sTH...

# ......
# ......
# ......
# ......
# s.TH..

# ......
# ......
# ......
# ......
# s..TH.

# == U 4 ==

# ......
# ......
# ......
# ....H.
# s..T..

# ......
# ......
# ....H.
# ....T.
# s.....

# ......
# ....H.
# ....T.
# ......
# s.....

# ....H.
# ....T.
# ......
# ......
# s.....

# == L 3 ==

# ...H..
# ....T.
# ......
# ......
# s.....

# ..HT..
# ......
# ......
# ......
# s.....

# .HT...
# ......
# ......
# ......
# s.....

# == D 1 ==

# ..T...
# .H....
# ......
# ......
# s.....

# == R 4 ==

# ..T...
# ..H...
# ......
# ......
# s.....

# ..T...
# ...H..
# ......
# ......
# s.....

# ......
# ...TH.
# ......
# ......
# s.....

# ......
# ....TH
# ......
# ......
# s.....

# == D 1 ==

# ......
# ....T.
# .....H
# ......
# s.....

# == L 5 ==

# ......
# ....T.
# ....H.
# ......
# s.....

# ......
# ....T.
# ...H..
# ......
# s.....

# ......
# ......
# ..HT..
# ......
# s.....

# ......
# ......
# .HT...
# ......
# s.....

# ......
# ......
# HT....
# ......
# s.....

# == R 2 ==

# ......
# ......
# .H....  (H covers T)
# ......
# s.....

# ......
# ......
# .TH...
# ......
# s.....
# After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

# ..##..
# ...##.
# .####.
# ....#.
# s###..
# So, there are 13 positions the tail visited at least once.

# Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?

data = open('data/day9.txt').read().splitlines()
commands = []
for line in data:
    line = line.split(' ')
    commands.append([line[0],line[1]])
        
        
#define starting position s, tail position t, and head position h
s = [0,0]
t = [0,0]
h = [0,0]
#set up a list of all the positions the tail has been to
tail_positions = []
tail_positions.append(s)

for move in commands[0:2000]:
    #get the direction and distance
    direction = move[0]
    distance = int(move[1])
    for i in range(distance):
        #move the head
        if direction == 'R':
            h[0] += 1
        elif direction == 'L':
            h[0] -= 1
        elif direction == 'D':
            h[1] += 1
        elif direction == 'U':
            h[1] -= 1
        #if the head is two steps away from the tail, move the tail
        if abs(h[0] - t[0]) > 1 or abs(h[1] - t[1]) > 1:
            if h[0] > t[0]:
                t[0] += 1
            elif h[0] < t[0]:
                t[0] -= 1
            if h[1] > t[1]:
                t[1] += 1
            elif h[1] < t[1]:
                t[1] -= 1            
            tail = t[:]
            tail_positions.append(tail)
# find the max width and height of the grid
# print(commands[1995:1998])
# max_width = 0
# max_height = 0
# for position in tail_positions:
#     if position[0] > max_width:
#         max_width = position[0]
#     if position[1] > max_height:
#         max_height = position[1]
# #print s, t and h in a grid
# for i in range(-120,120):
#     for j in range(-120,120):
#         if [j,i] == s:
#             print('s', end='')
#         elif [j,i] == t:
#             print('t', end='')
#         elif [j,i] == h:
#             print('h', end='')
#         elif [j,i] in tail_positions:
#             print('#', end='')
#         else:
#             print('.', end='')
#     print()
# print()
#print grid and # for each position the tail has been to
# for i in range (-120,120):
#     for j in range(-120,120):
#         if [j,i] in tail_positions:
#             print('#', end='')
#         else:
#             print('.', end='')
#     print()

#count the number of positions the tail has been to and dont count the same position twice. include s
print(len(tail_positions))
#turn each tail posisiton list into string
for i in range(len(tail_positions)):
    tail_positions[i] = str(tail_positions[i])
#remove duplicates
unique_tail_positions = []
for i in tail_positions:
    if i not in unique_tail_positions:
        unique_tail_positions.append(i)
count = 0
#use set to remove duplicates
print(len(unique_tail_positions))